version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8888
    depends_on:
      - backend
  timescaledb: 
    image: docker.io/timescale/timescaledb:2.2.0-pg13
    env_file: ./env/postgres.env 
    expose: 
      - 5432
  backend:
    build: ./backend
    expose: 
      - 8000
    depends_on:
      - timescaledb
      - worker
  worker:
    build: ./worker
    entrypoint: celery -A portfolio_worker worker -c 2 --loglevel=info -Q default,celery
    depends_on:
      - rabbit
      - redisdb
      - timescaledb
  rabbit:
    image: rabbitmq:3.8.9
    hostname: "rabbit"
    env_file: ./env/rabbit.env
    expose:
      - 5672
      - 15672
  redisdb:
    build: ./redis
    hostname: redisdb
    volumes:
      - ./redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    expose:
      - 6379