version: "3.8"
services:
  frontend:
    build: ./frontend
    volumes:
      - type: bind
        source: /Users/philiprumman/Projects/financial-portfolio/frontend
        target: /app
    ports:
      - 8080:80
    depends_on:
      - backend
  postgres:
    image: docker.io/postgres:13.1
    env_file: ./env/postgres.env
    ports:
      - 5432:5432
  backend:
    build: ./backend
    #entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python3 main.py
    volumes:
      - type: bind
        source: /Users/philiprumman/Projects/financial-portfolio/backend/main.py
        target: /app/main.py
      - type: bind
        source: /Users/philiprumman/Projects/financial-portfolio/backend/database.py
        target: /app/database.py
    depends_on:
      - postgres
      - rabbit
  worker:
    image: docker.io/celery_simple:latest
    entrypoint: celery -A celery_worker worker -c 2 --loglevel=info
  rabbit:
    image: rabbitmq:3.8.9
    hostname: "rabbit"
    env_file: ./env/rabbit.env
    expose:
      - 5672